########################################################
##请注意：application-dev.properties里的选项会覆盖本文件的配置
##这里请配置一些不会随环境变化而变化的配置项
##和环境相关的配置项，请在application-dev.properties里配置
########################################################

eveb:
    jwt:
        # 加密秘钥
        secret: EVEB123456789
        # token有效时长，半个小时，单位秒
        expire: 86400
        # 找回密码秘钥
        secretFindPwd: EVEB0987654321
        # 找回密码秘钥token有效时长，半个小时，单位秒
        expireFindPwd: 86400
        header: token